# Generated by Django 3.1.2 on 2020-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groceries', models.CharField(max_length=200, null=True)),
                ('outsideFood', models.CharField(max_length=200, null=True)),
                ('coffee', models.CharField(max_length=200, null=True)),
                ('gas', models.CharField(max_length=200, null=True)),
                ('rentMorgage', models.CharField(max_length=200, null=True)),
                ('LivingReparis', models.CharField(max_length=200, null=True)),
                ('medical', models.CharField(max_length=200, null=True)),
                ('schoolFees', models.CharField(max_length=200, null=True)),
                ('shoppingElectronics', models.CharField(max_length=200, null=True)),
                ('shoppingFashion', models.CharField(max_length=200, null=True)),
                ('kitchenEquipment', models.CharField(max_length=200, null=True)),
                ('legalPayments', models.CharField(max_length=200, null=True)),
                ('childCare', models.CharField(max_length=200, null=True)),
                ('enjoyment', models.CharField(max_length=200, null=True)),
                ('creditCard', models.CharField(max_length=200, null=True)),
                ('petFees', models.CharField(max_length=200, null=True)),
                ('selfCareselfDevlopment', models.CharField(max_length=200, null=True)),
                ('gym', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
