# Generated by Django 3.1.2 on 2020-11-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='statment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateInput', models.CharField(max_length=200, null=True)),
                ('termLength', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
