# Generated by Django 3.1.2 on 2020-11-07 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_statment'),
    ]

    operations = [
        migrations.AddField(
            model_name='statment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.category'),
        ),
        migrations.AddField(
            model_name='statment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.user'),
        ),
    ]
