# Generated by Django 3.1.2 on 2020-11-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20201106_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='statment',
            name='paycheck',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
